language: rust
rust:
    - nightly
    - beta
    - stable
cache: cargo
os:
    - linux
    - windows
    - osx

install:
    - wget https://github.com/jedisct1/libsodium/releases/download/1.0.10/libsodium-1.0.10.tar.gz
    - tar xvfz libsodium-1.0.10.tar.gz
    - cd libsodium-1.0.10 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
      cd ..
    - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
    - export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
