language: rust
rust:
    - nightly
    - stable
cache: cargo
os:
    - linux
    - osx

install:
    - curl -L -O https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz
    - tar xvfz libsodium-1.0.18.tar.gz
    - cd libsodium-1.0.18 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
      cd ..
    - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
    - export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
script:
    - cd memsec-test
    - cargo test --no-default-features
    - cargo test
    - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test --features nightly; fi
    - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo bench --features nightly; fi
