[package]
name = "memsec"
version = "0.2.3"
authors = ["quininer kel <quininer@live.com>"]
description = "Rust implementation `libsodium/utils`."
repository = "https://github.com/quininer/memsec"
keywords = [ "protection", "memory", "secure" ]
documentation = "https://docs.rs/memsec/"
license = "MIT"

[dependencies]
rand = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
mach_o_sys = "0.1"

[dev-dependencies]
libc = "0.2"
quickcheck = "0.4"

[target.'cfg(unix)'.dev-dependencies]
libsodium-sys = "0.0"
nix = "0.7"
