[package]
name = "memsec"
version = "0.3.0"
authors = ["quininer kel <quininer@live.com>"]
description = "Rust implementation `libsodium/utils`."
repository = "https://github.com/quininer/memsec"
keywords = [ "protection", "memory", "secure" ]
documentation = "https://docs.rs/memsec/"
license = "MIT"

[dependencies]
rand = { version = "0.3", optional = true }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.2", optional = true }
kernel32-sys = { version = "0.2", optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
mach_o_sys = { version = "0.1", optional = true }

[features]
default = [ "alloc" ]
use_os = [ "libc", "winapi", "kernel32-sys", "mach_o_sys" ]
alloc = [ "use_os", "rand" ]
