[package]
name = "memsec"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
libc = "0.2"
rand = "0.3"
errno = "0.1"
winapi = "0.2"
kernel32-sys = "0.2"

[dev-dependencies]
nix = "0.6"
