[package]
name = "memsec"
version = "0.1.6"
authors = ["quininer kel <quininer@live.com>"]
description = "Rust implementation `libsodium/utils`."
repository = "https://github.com/quininer/memsec"
license = "MIT"

[dependencies]
rand = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
libsodium-sys = "0.0.10"
quickcheck = "0.2"

[target.'cfg(unix)'.dev-dependencies]
nix = "0.6"
