[package]
name = "memsec-test"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
publish = false

[dependencies.memsec]
path = ".."
default-features = false

[dev-dependencies]
libc = "0.2"
quickcheck = "0.8"

[target.'cfg(unix)'.dev-dependencies]
libsodium-sys = { version = "0.2", features = [ "use-pkg-config" ] }
nix = "0.13"

[features]
default = [ "alloc", "use_os" ]
nightly = [ "memsec/nightly" ]
use_os = [ "memsec/use_os" ]
alloc = [ "memsec/alloc" ]
